# Generated by Django 4.2.16 on 2024-09-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('normal', '普通签到'), ('gesture', '手势签到'), ('location', '位置签到'), ('qr_code', '二维码签到'), ('checkin_code', '签到码')], max_length=20)),
                ('duration', models.IntegerField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('late_duration', models.IntegerField()),
                ('isPhoto', models.BooleanField(default=False)),
                ('gesture_code', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('isUpdate', models.BooleanField(default=False)),
                ('update_frequency', models.IntegerField(blank=True, null=True)),
                ('checkin_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CheckinActivity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CheckinForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', '已签到'), ('late', '迟到'), ('absent', '未签到')], default='absent', max_length=10)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='attendance.checkinactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accounts.student')),
            ],
            options={
                'db_table': 'CheckinForm',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='checkinactivity',
            name='classes',
            field=models.ManyToManyField(blank=True, to='attendance.class'),
        ),
        migrations.AddField(
            model_name='checkinactivity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.CreateModel(
            name='Activity_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.checkinactivity')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
            ],
            options={
                'db_table': 'ActivityClass',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='checkinform',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='unique_checkin'),
        ),
        migrations.AddConstraint(
            model_name='activity_class',
            constraint=models.UniqueConstraint(fields=('activity_id', 'class_id'), name='unique_activity_class'),
        ),
    ]
