# Generated by Django 4.2.16 on 2024-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinactivity',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
