# Generated by Django 4.2.16 on 2024-10-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_message_msg_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_type',
        ),
    ]
