# Generated by Django 4.2.16 on 2024-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_message_msg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinform',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='check_photo/'),
        ),
    ]
