# Generated by Django 4.2.16 on 2024-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_checkinform_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinactivity',
            name='checkin_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
