# Generated by Django 4.2.16 on 2024-11-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_checkinactivity_checkin_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinactivity',
            name='released',
        ),
    ]
