# Generated by Django 4.2.16 on 2024-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_checkinactivity_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinactivity',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
