# Generated by Django 4.2.16 on 2024-09-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(db_column='SNo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SName', max_length=100)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], db_column='SGender', max_length=1)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(db_column='TNo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TName', max_length=100)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], db_column='TGender', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': True,
            },
        ),
    ]
